/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizza;

import java.util.ArrayList;

/**
 *
 * @author mariam hasanat
 */


public class GUI extends javax.swing.JFrame {

    ArrayList<Pan> allOrders = new ArrayList<>();
    private int panSize;
    private int panType;
    public int getPanSize() {
        return panSize;
    }

    public void setPanSize(int panSize) {
        this.panSize = panSize;
    }
    
    Pan p1 = new Pan(panSize, panType);
    
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        javax.swing.ButtonGroup buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        garlic = new javax.swing.JCheckBox();
        small = new javax.swing.JRadioButton();
        oregano = new javax.swing.JCheckBox();
        meduim = new javax.swing.JRadioButton();
        redPeppers = new javax.swing.JCheckBox();
        large = new javax.swing.JRadioButton();
        olives = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        souce = new javax.swing.JCheckBox();
        deepDish = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pan = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mozerCheese = new javax.swing.JCheckBox();
        tomato = new javax.swing.JCheckBox();
        onion = new javax.swing.JCheckBox();
        viewInformation = new javax.swing.JButton();
        newOrder = new javax.swing.JButton();
        confirmTheOrder = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza Machine");

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Choose the size of pizza ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));

        garlic.setText("Garlic");
        garlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garlicActionPerformed(evt);
            }
        });

        buttonGroup1.add(small);
        small.setText("Small");
        small.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallActionPerformed(evt);
            }
        });

        oregano.setText("Oregano");
        oregano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oreganoActionPerformed(evt);
            }
        });

        buttonGroup1.add(meduim);
        meduim.setText("Medium");
        meduim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meduimActionPerformed(evt);
            }
        });

        redPeppers.setText("Red peppers");
        redPeppers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redPeppersActionPerformed(evt);
            }
        });

        buttonGroup1.add(large);
        large.setText("Large");
        large.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeActionPerformed(evt);
            }
        });

        olives.setText("Olives");
        olives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olivesActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setText("Choose the type of pizza ");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));

        souce.setText("Pizza Sauce");
        souce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                souceActionPerformed(evt);
            }
        });

        buttonGroup2.add(deepDish);
        deepDish.setText("Deep dish");
        deepDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deepDishActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup2.add(pan);
        pan.setText("Pan");
        pan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 255, 102));
        jLabel4.setText("Choose the toppings as you wish  ");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));

        jLabel5.setBackground(new java.awt.Color(102, 255, 102));
        jLabel5.setText("Pizza Informations : ");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 255)));

        mozerCheese.setText("Mozzarella Cheese");
        mozerCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mozerCheeseActionPerformed(evt);
            }
        });

        tomato.setText("Tomatoes");
        tomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomatoActionPerformed(evt);
            }
        });

        onion.setText("Onion");
        onion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onionActionPerformed(evt);
            }
        });

        viewInformation.setText("View Information");
        viewInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInformationActionPerformed(evt);
            }
        });

        newOrder.setText("New Order");
        newOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderActionPerformed(evt);
            }
        });

        confirmTheOrder.setText("Confirm the order");
        confirmTheOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmTheOrderActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(confirmTheOrder)
                        .addGap(18, 18, 18)
                        .addComponent(newOrder)
                        .addGap(18, 18, 18)
                        .addComponent(viewInformation))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pan)
                    .addComponent(deepDish)
                    .addComponent(large)
                    .addComponent(meduim)
                    .addComponent(small)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mozerCheese)
                            .addComponent(tomato)
                            .addComponent(onion)
                            .addComponent(garlic))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oregano)
                            .addComponent(redPeppers)
                            .addComponent(olives)
                            .addComponent(souce)))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(small)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(meduim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(large)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deepDish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mozerCheese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tomato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(garlic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(souce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oregano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(olives)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(redPeppers)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewInformation)
                    .addComponent(newOrder)
                    .addComponent(confirmTheOrder))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallActionPerformed
        // TODO add your handling code here:
        if (small.isEnabled()) {
            panSize = 1;
        }
    }//GEN-LAST:event_smallActionPerformed

    private void souceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_souceActionPerformed
        // TODO add your handling code here:
    Ingredient pizzaSauce = new Ingredient("Pizza Sauce", 56 * panSize, 28 * panSize);
    }//GEN-LAST:event_souceActionPerformed

    private void deepDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deepDishActionPerformed
        // TODO add your handling code here:
        if(deepDish.isEnabled())
            panType = 2;
    }//GEN-LAST:event_deepDishActionPerformed

    private void olivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olivesActionPerformed
        // TODO add your handling code here:
    Ingredient olives = new Ingredient("Olives ", 10 * panSize, 31 * panSize);
    }//GEN-LAST:event_olivesActionPerformed

    private void mozerCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mozerCheeseActionPerformed
        // TODO add your handling code here:
        Ingredient mozzarellaCheese = new Ingredient("Mozzarella Cheese", 170 * panSize, 476 * panSize); // index : 1
      
    }//GEN-LAST:event_mozerCheeseActionPerformed

    private void oreganoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oreganoActionPerformed
        // TODO add your handling code here:
    Ingredient oregano = new Ingredient("Oregano ", 10 * panSize, 31 * panSize);
    }//GEN-LAST:event_oreganoActionPerformed

    private void redPeppersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redPeppersActionPerformed
        // TODO add your handling code here:
    Ingredient redPeppers = new Ingredient("Red peppers", 10 * panSize, 31 * panSize);
    }//GEN-LAST:event_redPeppersActionPerformed

    private void tomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomatoActionPerformed
        // TODO add your handling code here:
    Ingredient tomatoes = new Ingredient("Tomatoes", 120 * panSize, 22 * panSize);
    }//GEN-LAST:event_tomatoActionPerformed

    private void garlicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garlicActionPerformed
        // TODO add your handling code here:
    Ingredient garlic = new Ingredient("Garlic", 7 * panSize, 4 * panSize);
    }//GEN-LAST:event_garlicActionPerformed

    private void onionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onionActionPerformed
        // TODO add your handling code here:
    Ingredient onion = new Ingredient("Onion", 115 * panSize, 44 * panSize);
    }//GEN-LAST:event_onionActionPerformed

    private void meduimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meduimActionPerformed
        // TODO add your handling code here:
        if (meduim.isEnabled())
            panSize = 2;
    }//GEN-LAST:event_meduimActionPerformed

    private void largeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeActionPerformed
        // TODO add your handling code here:
        if(large.isEnabled())
            panSize = 3;
    }//GEN-LAST:event_largeActionPerformed

    private void panActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panActionPerformed
        // TODO add your handling code here:
        if(pan.isEnabled())
            panType = 1;
    }//GEN-LAST:event_panActionPerformed

    private void viewInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInformationActionPerformed
        // TODO add your handling code here:
        //if view is enabled then display the information on the Text Area
    }//GEN-LAST:event_viewInformationActionPerformed

    private void confirmTheOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmTheOrderActionPerformed
        // TODO add your handling code here:
        if(confirmTheOrder.isEnabled())
        {
            allOrders.add(p1);
        }
    }//GEN-LAST:event_confirmTheOrderActionPerformed

    private void newOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderActionPerformed
        // TODO add your handling code here:
        //if this botton is enabled then the screen will be cleared...
    }//GEN-LAST:event_newOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton confirmTheOrder;
    private javax.swing.JRadioButton deepDish;
    private javax.swing.JCheckBox garlic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton large;
    private javax.swing.JRadioButton meduim;
    private javax.swing.JCheckBox mozerCheese;
    private javax.swing.JButton newOrder;
    private javax.swing.JCheckBox olives;
    private javax.swing.JCheckBox onion;
    private javax.swing.JCheckBox oregano;
    private javax.swing.JRadioButton pan;
    private javax.swing.JCheckBox redPeppers;
    private javax.swing.JRadioButton small;
    private javax.swing.JCheckBox souce;
    private javax.swing.JCheckBox tomato;
    private javax.swing.JButton viewInformation;
    // End of variables declaration//GEN-END:variables
}
